//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.27 at 09:20:48 AM IST 
//


package com.fedex.testservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="effectiveTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="objId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="externalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="expirationTimestamp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerView" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerViewModelValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PhoneTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phcountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="areaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AddressTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetLine2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="streetLine3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addcountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "effectiveTimestamp",
    "objId",
    "externalId",
    "typeCode",
    "expirationTimestamp",
    "customerView",
    "customerViewModelValue",
    "companyTypeCode",
    "companyDescription",
    "phoneTypeCode",
    "phcountryCode",
    "areaCode",
    "phoneNumber",
    "extension",
    "addressTypeCode",
    "streetLine1",
    "streetLine2",
    "streetLine3",
    "city",
    "state",
    "postalCode",
    "addcountryCode"
})
@XmlRootElement(name = "addAccountRequest")
public class AddAccountRequest {

    @XmlElement(required = true)
    protected String effectiveTimestamp;
    protected int objId;
    @XmlElement(required = true)
    protected String externalId;
    @XmlElement(name = "TypeCode", required = true)
    protected String typeCode;
    @XmlElement(required = true)
    protected String expirationTimestamp;
    @XmlElement(required = true)
    protected String customerView;
    @XmlElement(required = true)
    protected String customerViewModelValue;
    @XmlElement(required = true)
    protected String companyTypeCode;
    @XmlElement(required = true)
    protected String companyDescription;
    @XmlElement(name = "PhoneTypeCode", required = true)
    protected String phoneTypeCode;
    @XmlElement(required = true)
    protected String phcountryCode;
    @XmlElement(required = true)
    protected String areaCode;
    @XmlElement(required = true)
    protected String phoneNumber;
    @XmlElement(required = true)
    protected String extension;
    @XmlElement(name = "AddressTypeCode", required = true)
    protected String addressTypeCode;
    @XmlElement(required = true)
    protected String streetLine1;
    @XmlElement(required = true)
    protected String streetLine2;
    @XmlElement(required = true)
    protected String streetLine3;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String postalCode;
    @XmlElement(required = true)
    protected String addcountryCode;

    /**
     * Gets the value of the effectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveTimestamp() {
        return effectiveTimestamp;
    }

    /**
     * Sets the value of the effectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveTimestamp(String value) {
        this.effectiveTimestamp = value;
    }

    /**
     * Gets the value of the objId property.
     * 
     */
    public int getObjId() {
        return objId;
    }

    /**
     * Sets the value of the objId property.
     * 
     */
    public void setObjId(int value) {
        this.objId = value;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the expirationTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationTimestamp() {
        return expirationTimestamp;
    }

    /**
     * Sets the value of the expirationTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationTimestamp(String value) {
        this.expirationTimestamp = value;
    }

    /**
     * Gets the value of the customerView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerView() {
        return customerView;
    }

    /**
     * Sets the value of the customerView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerView(String value) {
        this.customerView = value;
    }

    /**
     * Gets the value of the customerViewModelValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerViewModelValue() {
        return customerViewModelValue;
    }

    /**
     * Sets the value of the customerViewModelValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerViewModelValue(String value) {
        this.customerViewModelValue = value;
    }

    /**
     * Gets the value of the companyTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyTypeCode() {
        return companyTypeCode;
    }

    /**
     * Sets the value of the companyTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyTypeCode(String value) {
        this.companyTypeCode = value;
    }

    /**
     * Gets the value of the companyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyDescription() {
        return companyDescription;
    }

    /**
     * Sets the value of the companyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyDescription(String value) {
        this.companyDescription = value;
    }

    /**
     * Gets the value of the phoneTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneTypeCode() {
        return phoneTypeCode;
    }

    /**
     * Sets the value of the phoneTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneTypeCode(String value) {
        this.phoneTypeCode = value;
    }

    /**
     * Gets the value of the phcountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhcountryCode() {
        return phcountryCode;
    }

    /**
     * Sets the value of the phcountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhcountryCode(String value) {
        this.phcountryCode = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the addressTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressTypeCode() {
        return addressTypeCode;
    }

    /**
     * Sets the value of the addressTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressTypeCode(String value) {
        this.addressTypeCode = value;
    }

    /**
     * Gets the value of the streetLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetLine1() {
        return streetLine1;
    }

    /**
     * Sets the value of the streetLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetLine1(String value) {
        this.streetLine1 = value;
    }

    /**
     * Gets the value of the streetLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetLine2() {
        return streetLine2;
    }

    /**
     * Sets the value of the streetLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetLine2(String value) {
        this.streetLine2 = value;
    }

    /**
     * Gets the value of the streetLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetLine3() {
        return streetLine3;
    }

    /**
     * Sets the value of the streetLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetLine3(String value) {
        this.streetLine3 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the addcountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddcountryCode() {
        return addcountryCode;
    }

    /**
     * Sets the value of the addcountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddcountryCode(String value) {
        this.addcountryCode = value;
    }

}
